### ISSUE TITLE
atomic instructions are not supported

### ISSUE THREAD

**Issue by JIMXGtamods** [Rerumu/Wasynth#44]
I have this error: Unsupported instruction: I32AtomicRmwAdd { memarg: MemArg { align: 2, max_align: 2, offset: 8, memory: 0 } }
I been trying to upgrade the code to support atomic functions but i can't :(
Solution?

**Comment by Rerumu** [comment]
Sadly, there are no plans to further extend this version of Wasynth with any of the proposals like atomics or SIMD and such. You'd likely need your compiler to not emit that code if possible or alter it to work with host workarounds.

There is a Wasynth rewrite in the works that will tackle most proposals and fix this too, but I have no real ETA for it.

**Comment by JIMXGtamods** [comment]
ty

**Comment by JIMXGtamods** [comment]
> Sadly, there are no plans to further extend this version of Wasynth with any of the proposals like atomics or SIMD and such. You'd likely need your compiler to not emit that code if possible or alter it to work with host workarounds.
> 
> There is a Wasynth rewrite in the works that will tackle most proposals and fix this too, but I have no real ETA for it.

I found a way for atomics support, i have made the lua functions, i add the names in Wasynth but last problem wasmparser (wasm-tools)'s Operator Enum doesn't contains atomics operators. What can i do?

error[E0533]: expected unit struct, unit variant or constant, found struct variant `Operator::MemoryAtomicNotify`
   --> wasm-ast\src\node.rs:242:4
    |
242 |             Operator::MemoryAtomicNotify => Self::MemoryAtomicNotify,
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not a unit struct, unit variant or constant

error[E0533]: expected unit struct, unit variant or constant, found struct variant `Operator::MemoryAtomicWait32`
   --> wasm-ast\src\node.rs:243:4
    |
243 |             Operator::MemoryAtomicWait32 => Self::MemoryAtomicWait32,
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not a unit struct, unit variant or constant

error[E0533]: expected unit struct, unit variant or constant, found struct variant `Operator::MemoryAtomicWait64`
   --> wasm-ast\src\node.rs:244:4
    |
244 |             Operator::MemoryAtomicWait64 => Self::MemoryAtomicWait64,
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not a unit struct, unit variant or constant

error[E0533]: expected unit struct, unit variant or constant, found struct variant `Operator::I32AtomicRmwAdd`
   --> wasm-ast\src\node.rs:393:4
    |
393 |             Operator::I32AtomicRmwAdd => Self::I32AtomicRmwAdd,
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^ not a unit struct, unit variant or constant

error[E0533]: expected unit struct, unit variant or constant, found struct variant `Operator::I64AtomicRmwAdd`
   --> wasm-ast\src\node.rs:394:4
    |
394 |             Operator::I64AtomicRmwAdd => Self::I64AtomicRmwAdd,
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^ not a unit struct, unit variant or constant

error[E0533]: expected unit struct, unit variant or constant, found struct variant `Operator::I32AtomicRmw8AddU`
   --> wasm-ast\src\node.rs:395:4
    |
395 |             Operator::I32AtomicRmw8AddU => Self::I32AtomicRmw8AddU,
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^ not a unit struct, unit variant or constant

**Comment by Rerumu** [comment]
I think you may be missing a feature flag somewhere. Extensions in `wasmparser` are gated behind feature flags based on their proposal name.

**Comment by JIMXGtamods** [comment]
> I think you may be missing a feature flag somewhere. Extensions in `wasmparser` are gated behind feature flags based on their proposal name.

Thanks for the reply, the wasmparser wasn't enough recent to include atomic operations so i update it to the latest (i had to change some lines). Now the code seems to be working, i included the atomic operations. I built it, but when i launch wasm2luau.exe with the atomic wasm file, the stack array seems to be broken, i debug the issue and it was the atomic fault. Error: thread 'main' panicked at wasm-ast\src\stack.rs:82:29:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/std\src\panicking.rs:662
   1: core::panicking::panic_fmt
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/core\src\panicking.rs:74
   2: core::panicking::panic
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/core\src\panicking.rs:148
   3: core::option::unwrap_failed
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library/core\src\option.rs:2015
   4: enum2$<core::option::Option<enum2$<wasm_ast::node::Expression> > >::unwrap
             at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library\core\src\option.rs:965
   5: wasm_ast::stack::Stack::pop
             at D:\Downloads\Wasynth-trunk\Wasynth-trunk\wasm-ast\src\stack.rs:82
   6: wasm_ast::factory::StatList::push_cmp_op
             at D:\Downloads\Wasynth-trunk\Wasynth-trunk\wasm-ast\src\factory.rs:214
   7: wasm_ast::factory::StatList::try_add_operation
             at D:\Downloads\Wasynth-trunk\Wasynth-trunk\wasm-ast\src\factory.rs:251
   8: wasm_ast::factory::Factory::add_instruction
             at D:\Downloads\Wasynth-trunk\Wasynth-trunk\wasm-ast\src\factory.rs:479
   9: wasm_ast::factory::Factory::build_stat_list
             at D:\Downloads\Wasynth-trunk\Wasynth-trunk\wasm-ast\src\factory.rs:787
  10: wasm_ast::factory::Factory::create_indexed
             at D:\Downloads\Wasynth-trunk\Wasynth-trunk\wasm-ast\src\factory.rs:318
  11: codegen_luau::translator::build_func_list::closure$0 The problem is here: 
fn push_atomic_rmw(&mut self, atomic_type: AtomicRmwType, memarg: MemArg) {
		let memory = memarg.memory.try_into().unwrap();
		let offset = memarg.offset.try_into().unwrap();

		let data = Statement::AtomicRmw(AtomicRmw {
			atomic_type,
			memory,
			offset,
			value: self.stack.pop().into(),
			pointer: self.stack.pop().into(),
		});

		self.leak_memory_write(memory);
		self.code.push(data);
	}

	fn push_atomic_rmw_cmpxchg(&mut self, atomic_type: AtomicRmwCmpxchgType, memarg: MemArg) {
		let memory = memarg.memory.try_into().unwrap();
		let offset = memarg.offset.try_into().unwrap();

		let data = Statement::AtomicRmwCmpxchg(AtomicRmwCmpxchg {
			atomic_type,
			memory,
			offset,
			expected: self.stack.pop().into(),
			replacement: self.stack.pop().into(),
			pointer: self.stack.pop().into(),
		});

		self.leak_memory_write(memory);
		self.code.push(data);
	}

	fn push_atomic_wait(&mut self, atomic_type: AtomicWaitType, memarg: MemArg) {
		let memory = memarg.memory.try_into().unwrap();
		let offset = memarg.offset.try_into().unwrap();

		let data = Statement::AtomicWait(AtomicWait {
			atomic_type,
			memory,
			offset,
			expected: self.stack.pop().into(),
			timeout: self.stack.pop().into(),
			pointer: self.stack.pop().into(),
		});

		self.leak_memory_write(memory);
		self.code.push(data);
	}

	fn push_atomic_notify(&mut self, atomic_type: AtomicNotifyType, memarg: MemArg) {
		let memory = memarg.memory.try_into().unwrap();
		let offset = memarg.offset.try_into().unwrap();

		let data = Statement::AtomicNotify(AtomicNotify {
			atomic_type,
			memory,
			offset,
			count: self.stack.pop().into(),
			pointer: self.stack.pop().into(),
		});

		self.leak_memory_write(memory);
		self.code.push(data);
	} i don't know if the atomic instructions are related to statement or expression.

**Comment by Rerumu** [comment]
Due to the nature of Lua, I would honestly avoid making custom atomic statements in the AST altogether. Lua only really runs in one thread, and Wasynth doesn't support shared memories at all, so you might have better luck just making the atomic instruction codegen call the already existing code for construction non-atomic operations.

**Comment by JIMXGtamods** [comment]
> Due to the nature of Lua, I would honestly avoid making custom atomic statements in the AST altogether. Lua only really runs in one thread, and Wasynth doesn't support shared memories at all, so you might have better luck just making the atomic instruction codegen call the already existing code for construction non-atomic operations.

Thanks for the information but doing atomic instructions without implementing threads isn't what i want.
I think Wasynth can support shared memory, revamping the runtime.lua can resolve the problem.
For luajit i dont know cause i dont use this version of lua (i didn't do the atomic update for this version, it's useless for me), but in luau there is a little chance to be made.
The threads in luau seems to be correct, i already do the emscripten library in luau, it working.
But these taking me days, i will send a comment if i found a idea.
Thanks.

**Comment by JIMXGtamods** [comment]
> Due to the nature of Lua, I would honestly avoid making custom atomic statements in the AST altogether. Lua only really runs in one thread, and Wasynth doesn't support shared memories at all, so you might have better luck just making the atomic instruction codegen call the already existing code for construction non-atomic operations.

Good news, wasynth supports now passive data and thread. I have to test in roblox and upgrade my emscripten library to support threads!

**Comment by JIMXGtamods** [comment]
Hello, i think i made the thread expansion! I created all the features, and i have just a thing to fix. The WASM is using MemoryInit but the arguments are wrong? cause they overlapping each together: rt_store_fill(memory_at_0, 1024, 24, 0)
				rt_memory_init(memory_at_0, 0, 0, 151075)
				rt_store_fill(memory_at_0, 152355, 45, 0)
				rt_memory_init(memory_at_0, 0, 1, 3)
				rt_store_fill(memory_at_0, 152403, 47, 0)
				rt_memory_init(memory_at_0, 0, 2, 4)
				rt_store_fill(memory_at_0, 152454, 44, 0)
				rt_memory_init(memory_at_0, 0, 3, 7)
				rt_store_fill(memory_at_0, 152505, 41, 0)
				rt_memory_init(memory_at_0, 0, 4, 7)
				rt_store_fill(memory_at_0, 152553, 41, 0) There is the definition: let size = self.target.stack.pop().into();

				let destination = MemoryArgument {
					memory: mem.try_into().unwrap(),
					pointer: self.target.stack.pop().into(),
				};

				self.target.leak_memory_write(destination.memory);

				let data = Statement::MemoryInit(MemoryInit {
					destination,
					data_index,
					size,
				});

				self.target.code.push(data); I guess this is the source of the error, i watching the webassembly overview and it looks correct. Can you help fix it?

**Comment by JIMXGtamods** [comment]
I fixed the overlapping of memory init by getting the destination offset (which i misunderstood with source offset) so i finally run correctly the wasm, threads seems to work. But last problem, the wasm is calling the 0-index (based of the debug that i made) of the table list, which is nil. This problem, i had it since the beginning of this journey. Do you have a solution?

**Comment by Rerumu** [comment]
I don't really know sadly, and it might be an issue that takes some debugging to do since I don't quite remember exactly how a lot of the stuff in the project interacted with each other. I would say large feature adds like this are unlikely to be fully reviewed or merged also, as my resources are currently on the rewrite of the project.

**Comment by JIMXGtamods** [comment]
> I don't really know sadly, and it might be an issue that takes some debugging to do since I don't quite remember exactly how a lot of the stuff in the project interacted with each other. I would say large feature adds like this are unlikely to be fully reviewed or merged also, as my resources are currently on the rewrite of the project.

No problem.
The table index being 0 is unknown, the index come from a stored value. I searched the whole wasynth code and i see no problem. I use all optimizations combinaisons, no success. And today, i print out the calculated table index in my old code which he doesn't contains the atomic stuff, he prints 1651 so i add it in the latest code but i have a timeout error. Maybe the update contains some issues, but no glue.
